# Конфигурация для базы данных PostgreSQL.
database:
  host: "localhost"
  port: "5432"
  dbname: "hpdb"
  user: "pgadmin"
  password: "Pg@dmin2023"

# Конфигурация сервера, на котором работает приложение.
server:
  host: "localhost"
  port: "8787"

# Конфигурация для сервера аутентификации Keycloak.
key_cloak:
  host: "http://192.168.150.64"  # URL-адрес сервера Keycloak, который предоставляет сервисы аутентификации и авторизации.
  port: "8181"                   # Порт, на котором сервер Keycloak слушает входящие запросы.
  client_id: "new-client"        # Идентификатор клиента, который зарегистрирован в Keycloak. Используется для аутентификации.
  client_secret: "8Fh1H07XgC9xL9o4SoDDmLhTzH0AM1bu"  # Секретный ключ клиента, используемый для безопасного доступа к Keycloak.
  realm: "master"                # Realm (область) в Keycloak, где зарегистрирован клиент. Realms позволяют разделять конфигурации и пользователей.

# Конфигурация для подключения к Redis - системе управления базами данных в памяти.
redis:
  uri: "localhost:6379"
  username: ""
  password: ""
  db: 0

# Параметры для настройки двухфакторной аутентификации (2FA).
2fa_params:
  sms_2fa: true             # Флаг, указывающий, включена ли двухфакторная аутентификация через SMS.
  otp_url: "http://192.168.150.64:8339/otp"  # URL-адрес для генерации одноразовых паролей (OTP). Этот URL используется для получения OTP при 2FA.
  otp_lifetime: 120         # Время жизни одноразового пароля (OTP) в секундах. Устанавливает, как долго OTP будет действительным.
  otp_confirm_limit: 3      # Лимит на количество попыток ввода одноразового пароля. После превышения лимита пользователь может быть заблокирован.

# Параметры для настройки HTTP-клиента.
h_client:
  timeout: 20               # Тайм-аут для HTTP-запросов в секундах.
